CREATE DATABASE IF NOT EXISTS market;

USE market;

CREATE TABLE Category
(
    Id SERIAL PRIMARY KEY,
	CategoryName CHARACTER VARYING(150)
);
CREATE TABLE Product
(
    Id SERIAL PRIMARY KEY,
	ProductName CHARACTER VARYING(150),
    Description CHARACTER VARYING(150),
	Price DECIMAL,
	CategoryId INTEGER REFERENCES Category(Id)
);

CREATE TABLE Client
(
    Id SERIAL PRIMARY KEY,
	ClientName CHARACTER VARYING(150),
    Address CHARACTER VARYING(150),
	PhoneNumber CHARACTER VARYING(50)
);
CREATE TABLE Orders
(
    Id SERIAL PRIMARY KEY,
	ClientId INTEGER REFERENCES Client(Id),
    ProductId INTEGER REFERENCES Product(Id),
	ProductCount INTEGER
);